<?php
defined( 'THEME_DIR' ) || define( 'THEME_DIR', get_template_directory() );
defined( 'THEME_URI' ) || define( 'THEME_URI', get_template_directory_uri());
defined( 'THEMEHUNK_DIR' ) || define( 'THEMEHUNK_DIR', THEME_DIR . '/inc' );
defined( 'THEMEHUNK_URI' ) || define( 'THEMEHUNK_URI', THEME_URI . '/inc' );
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?','novelpro'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'novelpro'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'novelpro'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'novelpro'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'novelpro'));
define('NOTHING_FOUND',__('Nothing Found here', 'novelpro'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria.', 'novelpro'));
define('CATEGORIES',__('Categories', 'novelpro'));
define('ARCHIVES',__('Archives', 'novelpro'));
define('BLOG_ARCHIVES',__('Blog Archives', 'novelpro'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'novelpro'));
define('PAGE',__('Page %s', 'novelpro'));
define('SEARCH_RESULT',__('Search Results for: %s', 'novelpro'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'novelpro'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'novelpro'));
define('LCN_MAP',__('Location Map','novelpro'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'novelpro'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'novelpro'));
define('ABOUT',__('About: %s', 'novelpro'));
define('HOME_TEXT',__('Home', 'novelpro'));
define('THIS_ENTRY_WAS_POSTED_IN',__('This entry was posted in %1$s','novelpro'));
define('PERMALINK',__('permalink','novelpro'));
define('BOOKMARK_THE',__('Bookmark the','novelpro'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'novelpro'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'novelpro'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'novelpro'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'novelpro'));
define('SMT_CMT',__('Submit Comment', 'novelpro'));
define('LV_CMT',__('Leave a Comment', 'novelpro'));
define('OLDER_POSTS',__('&larr; Older posts', 'novelpro'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'novelpro'));
define('PREV_POST',__(' Previous Post', 'novelpro'));
define('NEXT_POST',__('Next Post ', 'novelpro'));
define('READ_MORE',__('Read More', 'novelpro'));
define('SND_MSG',__('Send Your Message', 'novelpro'));
define('RETURN_TO',__('Return to %s', 'novelpro'));
define('BY_AUTHOR',__('By %2$s', 'novelpro'));
define('VIEW_ALL_POST_BY',__('View all posts by %s', 'novelpro'));
define('PUBLISHED_BY',__('Published %2$s', 'novelpro'));
define('FULL_SIZE_IS_PIXEL',__('Full size is %s pixels', 'novelpro'));
define('LINK_TO_FULL_SIZE_IMAGE',__('Link to full-size image', 'novelpro'));
define('EDIT_TEXT',__('Edit', 'novelpro'));
define('CONTINUE_READING',__('Continue reading &rarr;', 'novelpro'));
define('PAGES_COLON',__('Pages:', 'novelpro'));
define('CONTINUE_READING_DOTS',__('Continue Reading', 'novelpro'));
define('POSTED_BY',__('Posted by', 'novelpro'));
define('AND_TAGGED',__('and tagged','novelpro'));
define('SMT_MSG',__('Submit Message','novelpro'));
define('CONTACT_NAME',__('Your Name','novelpro'));
define('CONTACT_EMAIL',__('Your Email','novelpro'));
define('CONTACT_MESSAGE',__('Your Message','novelpro'));
define('FORM_SEARCH',__('Search','novelpro'));
define('CMNT_CLSD',__('Comments are closed.','novelpro'));
define('NO_CMNT',__('No Comments','novelpro'));
define('ONE_CMNT',__('One Comments','novelpro'));
define('CMNT',__('Comments','novelpro'));
define('POST_TAGGED_WITH',__('Post Tag With :', 'novelpro'));
define('CONTACT_SUBJECT',__('Subject', 'novelpro'));
define('CONTACT_SUBMIT',__('Submit Message', 'novelpro'));
define('HOME_MENU',__('Main Menu', 'novelpro'));
define('FRONT_MENU',__('Front Menu', 'novelpro'));
define('NOVELPRO_POSTER_BG',get_template_directory_uri().'/images/slider1.jpg');
?>